name: Ansible CI

on:
  pull_request:
    branches: [main]
    paths:
      - "ansible/**"
      - ".github/workflows/ansible.yaml"
  push:
    branches: [main]
    paths:
      - "ansible/**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install ansible-lint boto3 botocore

      - name: Install Ansible collections
        run: ansible-galaxy collection install amazon.aws community.general

      - name: Run ansible-lint
        run: ansible-lint playbooks/site.yaml
        working-directory: ansible
        env:
          ANSIBLE_INVENTORY: inventory/ci_hosts  # static inventory for CI